const common = {
    STRING_FORMAT_ALARM_SETTINGS_APPOINTMENT_DATE: '예약일 {date} {time}',

    STRING_DIALOG_ALARM_SETTINGS_INFO_TITLE: '알림안내',
    STRING_DIALOG_ALARM_SETTINGS_INFO_CONTEXT: '알림날짜가 예약날짜보다 늦게 설정되었습니다. 다시 설정해주세요.',

    STRING_MESSAGE_BOX_NOTHING: '수신된 메시지가 없습니다.',
    STRING_MESSAGE_BOX_MEDICAL_CARD: '진료카드',

    STRING_CUSTOMER_CENTER_NO_DATA: '문의가 없습니다.',
    STRING_CUSTOMER_CENTER_REPLY: '[문의답변] ',
    STRING_CUSTOMER_CENTER_REPLY_COMPLETE: '답변완료',
    STRING_CUSTOMER_CENTER_WRITE: '문의 작성 ',
    STRING_CUSTOMER_CENTER_INQUIRY: '문의',
    STRING_CUSTOMER_CENTER_INQUIRY_PLACEHOLDER: '문의사항을 작성해주세요.',
    STRING_CUSTOMER_CENTER_WRITER_NAME: '문의자 ',
    STRING_CUSTOMER_CENTER_WRITER_CONTACT: '연락처 ',

    STRING_CUSTOMER_CENTER_SEND_SUCCESS: '문의가 성공적으로 등록되었습니다.',

    STRING_SETTINGS_SET_ALARM: '알림설정',
    STRING_SETTINGS_LABEL_SET_ALARM: '설정앱으로 이동',
    STRING_SETTINGS_BIO_AUTH: '생체인증',
    STRING_SETTINGS_OPEN_CARD_TO_SHAKE: '흔들어서 진료카드 열기',
    STRING_SETTINGS_LARGE_FONT: '큰글씨 사용',
    STRING_SETTINGS_POLICY: '개인정보처리방침',
    STRING_SETTINGS_TERMS: '이용약관',
    STRING_SETTINGS_VERSION: '버전정보',
    STRING_SETTINGS_ON: 'ON',
    STRING_SETTINGS_OFF: 'OFF',

    STRING_FORMAT_DIALOG_SETTINGS_VERSION_CONTEXT: '버전은 [{version}] 입니다.',
    STRING_DIALOG_SETTINGS_VERSION_TITLE: '버전정보',
    STRING_DIALOG_SETTINGS_BIO_TITLE: '생체 인증',
    STRING_DIALOG_SETTINGS_BIO_CONTEXT: '로그인 후 이용해주세요.',
    STRING_DIALOG_SETTINGS_BIO_SETTING_TITLE: '생체 인증 설정',
    STRING_DIALOG_SETTINGS_BIO_SETTING_FAIL_CONTEXT: '생체 인증 설정에 실패하였습니다. 다시 시도해주세요.',
    STRING_DIALOG_SETTINGS_BIO_SETTING_DISABLED_CONTEXT: '생체인증을 지원하지 않는 기기이거나 저장된 생체인증이 없습니다. 휴대폰의 설정에서 생체인증을 등록해주세요.',
    STRING_DIALOG_SETTINGS_BIO_DELETE_TITLE: '생체 인증 정보 삭제',
    STRING_DIALOG_SETTINGS_BIO_DELETE_CONTEXT: '생체 인증 정보를 삭제하였습니다.',
    STRING_DIALOG_SETTINGS_BIO_REGISTER_TITLE: '생체 인증 정보 등록',
    STRING_DIALOG_SETTINGS_BIO_REGISTER_CONTEXT: '생체 인증 등록에 성공하였습니다.',

    STRING_PARKING_VISIT_CHECK: '내원 확인',
    STRING_PARKING_NO_DATA_1: '오늘 받은 진료/검진 기록이 없습니다.',
    STRING_PARKING_NO_DATA_2: '당일 진료/검진 이력을 기준으로\n무료 주차시간이 적용됩니다.',
    STRING_PARKING_INFO_1: '무료 또는 사전 수납으로 자동 게이트 운영예정',
    STRING_PARKING_INFO_2: '무료 주차시간 안내',
    STRING_PARKING_INFO_TIME_OUTPATIENT: '- 외래진료: 8시간',
    STRING_PARKING_INFO_TIME_INPATIENT: '- 입원 · 퇴원 · 당일수술: 12시간',
    STRING_PARKING_INFO_TIME_CHECKUP: '- 일반검진: 4시간, 종합검진: 8시간',
    STRING_PARKING_INFO_TIME_VISIT: '- 방문차량(회차): 1시간',
    STRING_PARKING_CHECK: '주차 확인',

    STRING_TIMELINE_LIST: '이력 목록',
    STRING_TIMELINE_CALENDAR: '달력',

    STRING_CALENDAR_CAPTION_SELECTED_DATE: '선택한 날짜',
    STRING_CALENDAR_SCHEDULE_LENGTH: '{scheduleSize}건',
    STRING_CALENDAR_NOTHING: '내원이력이 없습니다.',
    STRING_APPOINTMENT_NOW: '바로 예약',

    STRING_PARKING_RECEIPT: '확인증 및 정산',
};

export { common };
